### ISSUE TITLE
RuntimeError: size of dimension does not match previous size, operand 1, dim 0.  

### ISSUE THREAD

**Issue by hahaha12379** [nnzhan/Graph-WaveNet#30]
I don't konw how to solve this problem,><,谢谢大家了
Traceback (most recent call last):
  File "train.py", line 177, in <module>
    main()
  File "train.py", line 88, in main
    metrics = engine.train(trainx, trainy[:,0,:,:])
  File "/home/mist/Graph-WaveNet-master/engine.py", line 17, in train
    output = self.model(input)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/mist/Graph-WaveNet-master/model.py", line 192, in forward
    x = self.gconv[i](x, new_supports)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/mist/Graph-WaveNet-master/model.py", line 36, in forward
    x1 = self.nconv(x,a)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/mist/Graph-WaveNet-master/model.py", line 13, in forward
    x = torch.einsum('ncvl,vw->ncwl',(x,A))
  File "/usr/local/lib/python3.6/dist-packages/torch/functional.py", line 342, in einsum
    return einsum(equation, *_operands)
  File "/usr/local/lib/python3.6/dist-packages/torch/functional.py", line 344, in einsum
    return _VF.einsum(equation, operands)  # type: ignore
RuntimeError: size of dimension does not match previous size, operand 1, dim 0

**Comment by Meelisha** [comment]
Were you able to figure out this issue?
