### ISSUE TITLE
AttributeError: 'gwnet' object has no attribute 'nodevec1'

### ISSUE THREAD

**Issue by haoruochen** [nnzhan/Graph-WaveNet#42]
test.py run result:
model load successfully
Adaptive adjacency matrix generation is skipped as 'nodevec1' or 'nodevec2' is not initialized.
Evaluate best model on test data for horizon 1, Test MAE: 2.9515, Test MAPE: 0.0718, Test RMSE: 5.1257
Evaluate best model on test data for horizon 2, Test MAE: 3.4770, Test MAPE: 0.0869, Test RMSE: 6.4396
Evaluate best model on test data for horizon 3, Test MAE: 3.9241, Test MAPE: 0.1013, Test RMSE: 7.3645
Evaluate best model on test data for horizon 4, Test MAE: 4.3461, Test MAPE: 0.1159, Test RMSE: 8.1222
Evaluate best model on test data for horizon 5, Test MAE: 4.7537, Test MAPE: 0.1299, Test RMSE: 8.7606
Evaluate best model on test data for horizon 6, Test MAE: 5.1344, Test MAPE: 0.1433, Test RMSE: 9.3124
Evaluate best model on test data for horizon 7, Test MAE: 5.5282, Test MAPE: 0.1584, Test RMSE: 9.8222
Evaluate best model on test data for horizon 8, Test MAE: 5.8895, Test MAPE: 0.1739, Test RMSE: 10.2632
Evaluate best model on test data for horizon 9, Test MAE: 6.2030, Test MAPE: 0.1886, Test RMSE: 10.6280
Evaluate best model on test data for horizon 10, Test MAE: 6.5186, Test MAPE: 0.2051, Test RMSE: 11.0065
Evaluate best model on test data for horizon 11, Test MAE: 6.7955, Test MAPE: 0.2194, Test RMSE: 11.3738
Evaluate best model on test data for horizon 12, Test MAE: 7.0273, Test MAPE: 0.2315, Test RMSE: 11.7210
On average over 12 horizons, Test MAE: 5.2124, Test MAPE: 0.1522, Test RMSE: 9.1616
Traceback (most recent call last):
  File "D:\lunwen\daima\Graph WaveNet\test.py", line 127, in <module>
    main()
  File "D:\lunwen\daima\Graph WaveNet\test.py", line 107, in main
    adp = F.softmax(F.relu(torch.mm(model.nodevec1, model.nodevec2)), dim=1)
  File "D:\Users\haoruochen\anaconda3\envs\py36env\lib\site-packages\torch\nn\modules\module.py", line 1178, in __getattr__
    type(self).__name__, name))
AttributeError: 'gwnet' object has no attribute 'nodevec1'

How can i solve this problem??

**Comment by Guoxc666** [comment]
how to write the right command to run test.py like the train command "python train.py --gcn_bool --adjtype doubletransition --addaptadj  --randomadj",please give me some help please!
